import type { ExpertInfo } from './constants'
import { getExpertAvatarUrl } from './cloudAssets'

export const EXPERTS: ExpertInfo[] = [
  {
    id: 'zhangminghua',
    name: '张明华',
    title: '高级税务顾问',
    experience: '18年经验',
    badge: '金牌',
    avatar: 'zhangminghua',
    avatarUrl: getExpertAvatarUrl('zhangminghua.png'),
    qualifications: '注册税务师、注册会计师',
    specialties: ['企业所得税', '增值税筹划', '税务稽查应对'],
    specialtySummary: '企业所得税、增值税筹划、税务稽查应对',
    intro: '从事税务咨询工作18年，服务过500余家中小企业，擅长企业税负优化与税务风险防控，曾协助多家企业成功应对税务稽查。',
    greeting: '您好，我是张明华，专注企业税务筹划与风险管理，欢迎咨询！',
    rating: 4.9,
    consultCount: 1280,
  },
  {
    id: 'liusiyuan',
    name: '刘思远',
    title: '资深财税顾问',
    experience: '12年经验',
    badge: '明星',
    avatar: 'liusiyuan',
    avatarUrl: getExpertAvatarUrl('liusiyuan.png'),
    qualifications: '注册会计师、税务师',
    specialties: ['股权架构设计', '并购重组', '个人所得税'],
    specialtySummary: '股权架构设计、并购重组、个人所得税',
    intro: '深耕股权架构与并购税务领域12年，为百余家创业公司提供股权设计与融资税务方案，熟悉各类股权激励工具的税务处理。',
    greeting: '您好，我是刘思远，擅长股权架构与并购税务，期待为您服务！',
    rating: 4.8,
    consultCount: 876,
  },
  {
    id: 'chenxuemei',
    name: '陈雪梅',
    title: '财税合规专家',
    experience: '15年经验',
    badge: '金牌',
    avatar: 'chenxuemei',
    avatarUrl: getExpertAvatarUrl('chenxuemei.png'),
    qualifications: '注册税务师、高级会计师',
    specialties: ['财务合规', '账务规范化', '双账处理'],
    specialtySummary: '财务合规、账务规范化、双账处理',
    intro: '15年财税合规经验，专注中小企业账务规范化与内控建设，帮助数百家企业完成财务合规整改，有效降低税务风险。',
    greeting: '您好，我是陈雪梅，专注财税合规与账务规范，欢迎咨询！',
    rating: 4.9,
    consultCount: 1050,
  },
  {
    id: 'wangjianguo',
    name: '王建国',
    title: '税务稽查专家',
    experience: '20年经验',
    badge: '专家',
    avatar: 'wangjianguo',
    avatarUrl: getExpertAvatarUrl('wangjianguo.png'),
    qualifications: '注册税务师、前税务局稽查科科长',
    specialties: ['税务稽查应对', '税务行政复议', '重大税务争议'],
    specialtySummary: '税务稽查应对、税务行政复议、重大税务争议',
    intro: '曾任职税务局稽查科20年，深谙稽查流程与应对策略，转型顾问后协助企业处理各类稽查案件，成功率极高。',
    greeting: '您好，我是王建国，专注税务稽查应对，有任何稽查问题欢迎咨询！',
    rating: 5.0,
    consultCount: 632,
  },
  {
    id: 'sunhaoran',
    name: '孙浩然',
    title: '商业财税顾问',
    experience: '10年经验',
    badge: '明星',
    avatar: 'sunhaoran',
    avatarUrl: getExpertAvatarUrl('sunhaoran.png'),
    qualifications: '注册会计师、MBA',
    specialties: ['商业模式分析', '融资税务', '财务数据分析'],
    specialtySummary: '商业模式分析、融资税务、财务数据分析',
    intro: '10年创业公司财税服务经验，擅长结合商业模式进行财税规划，服务过多家获得融资的科技与消费类企业。',
    greeting: '您好，我是孙浩然，擅长商业财税规划，欢迎咨询！',
    rating: 4.7,
    consultCount: 543,
  },
  {
    id: 'wuxiaofeng',
    name: '吴晓峰',
    title: '节税筹划专家',
    experience: '14年经验',
    badge: '金牌',
    avatar: 'wuxiaofeng',
    avatarUrl: getExpertAvatarUrl('wuxiaofeng.png'),
    qualifications: '注册税务师、注册会计师',
    specialties: ['节税方案设计', '税收优惠政策', '高新技术企业认定'],
    specialtySummary: '节税方案设计、税收优惠政策、高新技术企业认定',
    intro: '专注合法节税筹划14年，熟悉各地税收优惠政策，累计为客户节省税款超亿元，擅长高新技术企业与小微企业税务优化。',
    greeting: '您好，我是吴晓峰，专注合法节税方案，欢迎咨询！',
    rating: 4.8,
    consultCount: 920,
  },
  {
    id: 'linjiay',
    name: '林佳怡',
    title: '政策研究顾问',
    experience: '8年经验',
    badge: '新锐',
    avatar: 'linjiay',
    avatarUrl: getExpertAvatarUrl('linjiay.png'),
    qualifications: '税务师、经济师',
    specialties: ['税收政策解读', '地方优惠政策', '政策申报辅导'],
    specialtySummary: '税收政策解读、地方优惠政策、政策申报辅导',
    intro: '深耕税收政策研究8年，持续跟踪国家及各地最新税收优惠政策，擅长帮助企业识别并落地适用的政策红利。',
    greeting: '您好，我是林佳怡，专注税收政策研究与解读，欢迎咨询！',
    rating: 4.7,
    consultCount: 389,
  },
  {
    id: 'zhouqiming',
    name: '周启明',
    title: '企业财税顾问',
    experience: '11年经验',
    badge: '明星',
    avatar: 'zhouqiming',
    avatarUrl: getExpertAvatarUrl('zhouqiming.png'),
    qualifications: '注册会计师、税务师',
    specialties: ['中小企业财税', '税负检测', '风险预警'],
    specialtySummary: '中小企业财税、税负检测、风险预警',
    intro: '11年中小企业财税服务经验，擅长税负合理性分析与风险预警，帮助企业建立健康的财税管理体系。',
    greeting: '您好，我是周启明，专注中小企业财税健康管理，欢迎咨询！',
    rating: 4.8,
    consultCount: 710,
  },
  {
    id: 'zhaokaiwem',
    name: '赵凯文',
    title: '资深审计顾问',
    experience: '16年经验',
    badge: '专家',
    avatar: 'zhaokaiwem',
    avatarUrl: getExpertAvatarUrl('zhaokaiwem.png'),
    qualifications: '注册会计师、注册税务师',
    specialties: ['审计应对', '财务尽调', '内控建设'],
    specialtySummary: '审计应对、财务尽调、内控建设',
    intro: '16年审计与财税经验，曾任职四大会计师事务所，擅长企业审计应对与财务尽职调查，帮助企业完善内控体系。',
    greeting: '您好，我是赵凯文，专注审计应对与内控建设，欢迎咨询！',
    rating: 4.9,
    consultCount: 487,
  },
  {
    id: 'liting',
    name: '李婷',
    title: '个税与薪酬顾问',
    experience: '9年经验',
    badge: '新锐',
    avatar: 'liting',
    avatarUrl: getExpertAvatarUrl('liting.png'),
    qualifications: '税务师、人力资源管理师',
    specialties: ['个人所得税', '薪酬架构设计', '社保合规'],
    specialtySummary: '个人所得税、薪酬架构设计、社保合规',
    intro: '9年个税与薪酬领域专注经验，熟悉各类薪酬结构的税务处理，帮助企业和个人合理规划薪酬，降低个税负担。',
    greeting: '您好，我是李婷，专注个税与薪酬规划，欢迎咨询！',
    rating: 4.6,
    consultCount: 298,
  },
]
